<a href="https://colab.research.google.com/github/franklinemomanyi/MachineLearning/blob/main/24_Principal_Component_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
#Importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [16]:
#Importing Data
data  = pd.read_csv('Wine.csv')
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [17]:
#Splitting the dataset into training and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=0)

In [18]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test  = sc.fit_transform(x_test)

In [19]:
#Applying PCA
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
x_train = pca.fit_transform(x_train)
x_test  = pca.transform(x_test)

In [20]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [21]:
#Performance Evaluation
y_pred = classifier.predict(x_test)
#print(np.concatenate(( y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy: '+str(accuracy_score(y_test, y_pred)*100)+'%')

[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]
Accuracy: 97.22222222222221%
